kumuluzee:
  name: ape-job-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/APEJobDS
  graphql:
    mapping: graphql
    ui:
      enabled: true
    scanning:
      optimize: false
    defaults:
      offset: 0
      limit: 10
    exceptions:
      include-show-error-defaults: false
      show-exception-message: true
      show-error-message:
        - java.lang.Exception
        - java.lang.RuntimeException
        - javax.ws.rs.WebApplicationException
        - javax.ws.rs.NotFoundException
        - javax.ws.rs.NotAllowedException
        - java.time.DateTimeException
