package si.ape.job.services.machine;

public enum MoveType {

    ORDER_CONFIRMATION_SPECIALIST_TO_DELIVERY_DRIVER,
    DELIVERY_DRIVER_TO_WAREHOUSE_AGENT,
    WAREHOUSE_AGENT_TO_WAREHOUSE_AGENT,
    WAREHOUSE_AGENT_TO_INTERNATIONAL_DRIVER,
    INTERNATIONAL_DRIVER_TO_INTERNATIONAL_DRIVER,
    INTERNATIONAL_DRIVER_TO_WAREHOUSE_AGENT,
    WAREHOUSE_AGENT_TO_DELIVERY_DRIVER,
    DELIVERY_DRIVER_TO_DELIVERY_DRIVER,

}
