package si.ape.job.services.machine;

public enum StaffRole {

    ADMINISTRATOR,
    WAREHOUSE_MANAGER,
    WAREHOUSE_AGENT,
    DELIVERY_DRIVER,
    INTERNATIONAL_DRIVER,
    LOGISTICS_AGENT,
    ORDER_CONFIRMATION_SPECIALIST

}
